export const GET_LAYER = 'GET_LAYER';
export const GET_LAYER_SUCCEEDED = 'GET_LAYER_SUCCEEDED';
export const GET_LAYER_FAILED = 'GET_LAYER_FAILED';

export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM_SUCCEEDED = 'ADD_ITEM_SUCCEEDED';
export const ADD_ITEM_FAILED = 'ADD_ITEM_FAILED';

export const EDIT_ITEM = 'EDIT_ITEM';
export const EDIT_ITEM_SUCCEEDED = 'EDIT_ITEM_SUCCEEDED';
export const EDIT_ITEM_FAILED = 'EDIT_ITEM_FAILED';

export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ITEM_SUCCEEDED = 'DELETE_ITEM_SUCCEEDED';
export const DELETE_ITEM_FAILED = 'DELETE_ITEM_FAILED';